pub mod actions;
pub mod config;
pub mod credentials;
pub mod engine;
#[cfg(feature = "gui")]
pub mod gui;
pub mod mail_ops;
pub mod message;
pub mod notify;
pub mod paths;
pub mod rules;
pub mod store;
pub mod sync;
pub mod trash;
